#!/bin/sh

while true; do
    while true; do
        clip=$(powershell.exe -command 'Get-Clipboard' | tr --delete '\r')
        last_name="$name"
        name=$(echo "$clip" | rev | cut --delimiter '/' --fields '1' | rev)

        if [ "$last_name" != "$name" ]; then
            break
        fi

        sleep 1
    done

    packwiz modrinth add "$name"
    sleep 1
done
