name = "PistachioPlus"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10f4aab08711331736c96bed13dccf6ef1cb3691a2fc86094b3a03f399e0327c"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
