name = "PistachioPlus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3e5226112791d956f4669a229b2f655dd34be08931b8d82851d09ba913fdb85"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.4"]
