name = "PistachioPlus"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcfecdef2d038ef1ea85b6223e3b8187ceb3bef768981dbf8c159cc452aff804"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
