name = "PistachioPlus"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b23fb922c3c64eba81e221e1b2e50533e676dcd143e8d492eeb305bf244fdbc8"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
