name = "PistachioPlus"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "729bd27d40ecff6f897ea8a65f97d29812fbec7374316f281c6d921591ed8819"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
