name = "PistachioPlus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3293ee5536356bed8645e7e9b46d64d53a5cd4b686b1ac2d5319c18161544ba"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.4"]
