name = "PistachioPlus"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8b75a56109b349b11d1a5264c11245bea06f58619c6dee517a4bb4ff64baa64"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
