name = "PistachioPlus"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe847f1291ea24738c6b8e41b1e9123a16e7077e5fdf430c3a74884f0cd135fc"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
