name = "PistachioPlus"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5d521d895b23ff954ddc901cfd986c76a2b9ec9393cb4da982afdd57ee844c4"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
