name = "PistachioPlus"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4aed399030c9cd4b24c7a10abf15e78b4ff6e1741791e24ca9f3896b9af5c6f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.4"]
