---
name: "release"

on:
  push:
    paths:
      # only run when mods are changed
      - 'packwiz/pack.toml'
      - 'packwiz/index.toml'
      - 'packwiz/mods/*'
  workflow_dispatch:

jobs:
  pre-release:
    permissions: write-all
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          go install github.com/packwiz/packwiz@latest
          git clone https://github.com/cultab/pistachio_plus.git
          cd pistachio_plus/packwiz
          $HOME/go/bin/packwiz modrinth export

      - name: Generate new tag version
        id: version
        uses: "flynshue/version-action@v0.0.1"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.version.outputs.version }}"
          prerelease: false
          title: "Auto Release ${{ steps.version.outputs.version }}"
          files: |
            pistachio_plus/Readme.md
            pistachio_plus/packwiz/*.mrpack
          
