---
name: "release"

on:
  push:
    paths:
      # only run when mods are changed
      - 'packwiz/pack.toml'
      - 'packwiz/index.toml'
      - 'packwiz/mods/*'
  workflow_dispatch:

jobs:
  pre-release:
    permissions: write-all
    name: "Auto release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Export to mrpack
        run: |
          go install github.com/packwiz/packwiz@latest
          git clone https://github.com/cultab/pistachio_plus.git
          cd pistachio_plus/packwiz
          $HOME/go/bin/packwiz modrinth export
          version=$(cat pack.toml | grep 'version ' | cut -f 2 -d '"')
          echo "version=${version}" >> $GITHUB_ENV

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.version }}"
          prerelease: false
          title: "v${{ env.version }}"
          files: |
            pistachio_plus/Readme.md
            pistachio_plus/packwiz/*.mrpack
          
