---
name: "release"

on:
  push:
    paths:
      # only run when mods are changed
      - 'packwiz/pack.toml'
      - 'packwiz/index.toml'
      - 'packwiz/mods/*'
  workflow_dispatch:

jobs:
  pre-release:
    permissions: write-all
    name: "Auto release"
    runs-on: "ubuntu-latest"

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v3
        with: 
          go-version: 1.19

      - name: Install packwiz
        run: |
          go install github.com/packwiz/packwiz@latest

      - name: Export to mrpack
        run: |
          cd packwiz
          $HOME/go/bin/packwiz modrinth export
          version=$(cat pack.toml | grep 'version ' | cut -f 2 -d '"')
          echo "version=${version}" >> $GITHUB_ENV

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.version }}"
          prerelease: false
          title: "v${{ env.version }}"
          files: |
            Readme.md
            packwiz/*.mrpack
          
